In [15]:
import torch
from torch import nn

import numpy as np

In [16]:
num_inputs = 2
num_examples = 1000
true_w = [2, -3.4]
true_b = 4.2
features = torch.tensor(np.random.normal(0, 1, (num_examples, num_inputs)), dtype=torch.float)
labels = true_w[0] * features[:, 0] + true_w[1] * features[:, 1] + true_b
labels += torch.tensor(np.random.normal(0, 0.01, size=labels.size()), dtype=torch.float)
import torch.utils.data as Data

batch_size = 10


##  nn.linear(input,output,(boolean)bias):<p>
input：输入神经元数<p>
output:输出神经元数<p>
根据这两个参数内部声明一个线性映射W和b,具体初始化值由下文nn.init执行<p>
bias:偏置向量b的有无（有则不是线性映射：F(0)!=0）<p>
input=x,output:=y,则<p>
y=Wx+b<p>
此处x,y均为m,nx1的<b>向量<b\><p>
此后X,Y的宽度为数据量

In [17]:
class LinearNet(nn.Module):
    def __init__(self, n_feature):
        super().__init__()
        self.linear = nn.Linear(n_feature, 1)
    # forward 定义前向传播
    def forward(self, x):
        y = self.linear(x)
        return y

net = LinearNet(num_inputs)
print(net) # 使用print可以打印出网络的结构


LinearNet(
  (linear): Linear(in_features=2, out_features=1, bias=True)
)


## nn.parameters()<p>
可以通过net.parameters()来查看模型所有的可学习参数，此函数将返回一个生成器。

In [20]:
print("W is:",[param for param in net.parameters()][0])
print("b is:",[param for param in net.parameters()][1])

W is: Parameter containing:
tensor([[ 0.0093, -0.0087]], requires_grad=True)
b is: Parameter containing:
tensor([0.], requires_grad=True)


## nn.init
init.normal_(obj,mean,std):将正态分布填充到obj中<p>
init.constant_(obj,val):将val赋予obj

In [23]:
from torch.nn import init

init.normal_(net.linear.weight, mean=0, std=0.01)#------------------------------初始化映射(矩阵)W，正态分布，均值为mean,标准差std
init.constant_(net.linear.bias, val=0)  # --------------------------------------初始化偏置向量b


Parameter containing:
tensor([[-0.0274,  0.0150]], requires_grad=True)

## nn.Sequential
事实上我们还可以用nn.Sequential来更加方便地搭建网络，Sequential是一个有序的容器，网络层将按照在传入Sequential的顺序依次被添加到计算图中。

In [ ]:
# 写法一
net = nn.Sequential(
    nn.Linear(num_inputs, 1)            #参数：size
    # 此处还可以传入其他层
    )

# 写法二
net = nn.Sequential()
net.add_module('linear', nn.Linear(num_inputs, 1))
# net.add_module ......

# 写法三
from collections import OrderedDict
net = nn.Sequential(OrderedDict([
          ('linear', nn.Linear(num_inputs, 1))
          # ......
        ]))

print(net)
print(net[0])
