# 自动求梯度
如果将属性tensor.requires_grad设置为True，它将开始追踪(track)在其上的所有操作（这样就可以利用链式法则进行梯度传播了）。完成计算后，可以调用.backward()来完成所有梯度计算。此Tensor的梯度将累积到自变量tensor的.grad属性中。<p>
<b>ex.:x->y->z,用z 进行z.backword(),梯度存储在x.grad中

————————————————————————————————————————————————————————————————————————
##  基本概念
 x=torch.tensor(......) ->y=f(x)->z=f(y)   z.backword() =>x.grad=dz/dx<p>
 标量对张量求导，求导结果是和自变量同形的张量。

In [19]:
import torch
x = torch.ones(2, 2, requires_grad=True)
print(x)
print(x.grad_fn)
y = x + 2
print(y)
print(y.grad_fn)
z = y * y * 3#位置乘法
 
out = z.mean()  
print(z,out)
print(type(z))


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[1., 2.],
        [3., 4.]]) tensor(2.5000)
<class 'torch.Tensor'>


.mean()是求算术平均,转化成一个一维tensor

In [10]:
print(out.backward() )# 等价于 out.backward(torch.tensor(1.))

None


In [12]:
print(x)
print(x.grad)


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [22]:
# 再来反向传播一次，注意grad是累加的
out2 = x.sum()
print(out2)
out2.backward()
print(x.grad)

out3 = x.sum()
x.grad.data.zero_()
out3.backward()
print(x.grad)


tensor(4., grad_fn=<SumBackward0>)
tensor([[2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.]])


——————————————————————————————————————————————————————————————————————
### 不允许张量对张量求导，只允许标量对张量求导，求导结果是和自变量同形的张量。

In [23]:
z=torch.tensor([[1.,2.],[3.,4.]])
w=torch.tensor([[[0.1,1.],[0.2,3.]]])
print(z*w)


tensor([[[ 0.1000,  2.0000],
         [ 0.6000, 12.0000]]])


tensor之间*是对应位算术乘法(位置乘法)，不是张量乘法

-----------------------------------------------
## .data

In [25]:
x = torch.ones(1,requires_grad=True)
y = 2 * x
y.data*=99# 只改变了值，不会记录在计算图，所以不会影响梯度传播
y.backward()
print(y) # 更改data的值也会影响tensor的值
print(x.grad)


tensor([198.], grad_fn=<MulBackward0>)
tensor([2.])
